### ISSUE TITLE
Cannot read property 'highestBid' of undefined

### ISSUE THREAD

**Issue by Blindmikey** [ethereum/ens-registrar-dapp#164]
After revealing my bid, I'm told that I'm the current highest bidder. 
Then after a few seconds, the language changes to "but since someone else was willing to pay more...", yet the highest bid amount and second place bid amount do not change, and the highest bid amount matches what I've revealed. 

Using MetaMask Chrome Extension. 

At the time of the language change I see the following in the console:
```
Exception in template helper: TypeError: Cannot read property 'highestBid' of undefined
    at Object.n (http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:207:2237)
    at http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:106:31360
    at http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:106:17194
    at http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:106:31993
    at Function.e._withTemplateInstanceFunc (http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:107:5707)
    at http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:106:31900
    at Object.p.call (http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:109:1929)
    at http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:206:2516
    at h.View.<anonymous> (http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:106:27999)
    at http://registrar.ens.domains/0d5f2b41f700927569c498856cd2adccf6f540b0.js:106:19036
```

**Comment by blindmikey** [comment]
Clicking the "Watch this" button seemed to resolve the issue somehow.
